version: '3.4'

services:
  app:
    image: gradle:7.4.1-jdk11-alpine
    build:
      context: .
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
    volumes:
      - '.:/app'
      - '~/.gradle/:/home/gradle/.gradle'
    command: gradle bootRun

  prometheus:
    image: prom/prometheus
    volumes:
      - '.:/etc/prometheus'
    ports:
      - '9090:9090'
    environment:
      SYSTEM_IP: "localhost"
      PROMETHEUS_IP: "localhost"


  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'

